/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppTabBar: typeof import('./components/AppTabBar.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
  }
}
